# Generated by Django 6.0.3 on 2026-03-22 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_quota', models.IntegerField(default=0)),
                ('work_schedule', models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time')], default='FT', max_length=2)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='docente_user', to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Docencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='docencia_user', to='accounts.user')),
            ],
        ),
    ]
