# Generated by Django 6.0.3 on 2026-03-22 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docencia',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='docente',
            old_name='user_id',
            new_name='user',
        ),
    ]
