services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: sh -c "if [ ! -f node_modules/@rolldown/binding-linux-x64-musl/rolldown-binding.linux-x64-musl.node ]; then npm install --include=optional --no-audit --no-fund; fi && npm run dev"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=1
      - POSTGRES_DB=dcc_catalog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
  
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dcc_catalog
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: