# Generated by Django 6.0.3 on 2026-03-22 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('term', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('credits', models.IntegerField(default=0)),
                ('tags', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offering_comment', models.TextField(blank=True)),
                ('type', models.CharField(blank=True, max_length=20)),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='courses.academicperiod')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.IntegerField(default=1)),
                ('mobility_quota', models.IntegerField(default=0)),
                ('service_quota', models.IntegerField(default=0)),
                ('control_count', models.IntegerField(default=0)),
                ('has_exam', models.BooleanField(default=False)),
                ('has_survey', models.BooleanField(default=False)),
                ('quota', models.IntegerField(default=0)),
                ('modality', models.CharField(choices=[('Presencial', 'Presencial'), ('Online', 'Online'), ('Híbrido', 'Híbrido'), ('Semipresencial', 'Semipresencial')], default='Presencial', max_length=20)),
                ('management_comment', models.TextField(blank=True)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.courseoffering')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('Cátedra', 'Cátedra'), ('Laboratorio', 'Laboratorio'), ('Auxiliar', 'Auxiliar')], default='Cátedra', max_length=20)),
                ('classroom', models.CharField(blank=True, max_length=50)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.section')),
            ],
        ),
    ]
