# Generated by Django 6.0.3 on 2026-03-22 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_rename_user_id_docencia_user_and_more'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.CharField(choices=[('Presencial', 'Presencial'), ('Remoto', 'Remoto'), ('Híbrido', 'Híbrido'), ('Semipresencial', 'Semipresencial')], max_length=20)),
                ('priority', models.IntegerField()),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='courses.courseoffering')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='accounts.user')),
            ],
        ),
    ]
